### ISSUE TITLE
Warning on disconnection of client

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#12]
Hi,
I'm launching the exampleServer and exampleClient provided with this project and compiled with VisualStudio 2015 under Win7 64bit by these command line calls:
```
start anyrpc\build\bin\Debug\exampleServer.exe jsontcp 9000 100
start anyrpc\build\bin\Debug\exampleClient.exe jsontcp 127.0.0.1 9000
```
At the moment the client finishes its job, the server displays the following warning:
![logmessage](https://cloud.githubusercontent.com/assets/7890485/16298364/5c26fe78-3935-11e6-9db8-1b160e97e607.PNG)
In my own project, I noticed that this warning always occurs, if a Jsontcp-client calls the close() function. It's probably not even related to the target system and compiler, because it also happens on linux with gcc.

Are you able to reproduce this warning?

**Comment by sgieseking** [comment]
It's surprisingly tricky to properly detect socket disconnects.  It seems to be timing related whether it will fail the socket.Receive call at the beginning of TcpConnection::ReadHeader or more gracefully detect it a little further down where it has `log_warn("EOF while reading header")`.  The results are the same with a call to Initialize() and return false.

It may be that the Receive call will reliably also indicate eof=true and this could generate a more correct message, but I have not tested this.

**Comment by JanPlitzkow** [comment]
I will probably look into this at a later point again. At the moment it's not that important to me, but I will post here if I figure something out...

**Comment by JanPlitzkow** [comment]
In my case, I never got the `log_warn("EOF while reading header");` but always the `log_warn("Error while reading header: " [...] );`. But that might not be universally valid.

Im running anyrpc on linux (compiled with gcc) and on windows (compiled with VisualStudio2015). The socket error codes differ on these systems, but I get:
- 10054 on Windows = "Connection reset by peer." (https://msdn.microsoft.com/en-gb/library/windows/desktop/ms740668(v=vs.85).aspx)
- 104 on Linux  = "Connection reset by peer." (http://www.virtsync.com/c-error-codes-include-errno)

MSDN further states for "connection reset by peer":
> An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close.

IMHO there should be a possibility for a client to disconnect from server without generating a warning on the server. For a "User" of the anyrpc-library the fact that a Client::Close() results in an warning on the server is confusing.
At the moment I see two possiblities:

1. Do not in generally log a warning after `socket_.Receive` failed in `TcpConnection::ReadHeader()` but check the error code first. If Its {windows,10054} or {linux,104} do not log a warning (maybe a log on lower level still).
2. Anyrpc should do a "graceful shutdown" of the TCP-connection. Normally a TCP-connection is closed with sending "FIN" - "FIN-ACK" - "ACK". Monitoring the anyrpc connection with wireshark only a "RST" is send, which is a forced shutdown. This might be caused by only calling `close()` / `closesocket() `and not `shutdown()` before, but my knowledge on this is very basic. 

You might find more information here: 
- http://stackoverflow.com/a/23483487
- https://msdn.microsoft.com/en-us/library/windows/desktop/ms738547(v=vs.85).aspx

In my opinion the second solution would be the better way, but also might be a little bit more complicated to program. What's your opinion on this?

**Comment by sgieseking** [comment]
The references also indicate closing a socket is a common way to terminate a connection, so the server needs to handle this situation.  A socket close() should initiate shutdown if it has not already been called.  From a client perspective, this should be the same as making consecutive calls.  So a client would need to call shutdown(), wait for an acknowledgement, then call close() - an added complexity.

From a perspective of how an rpc system works, there is not much of a reason to separate the two actions.  Generally, the client sends a message and then receives the result.  When the client closes a connection, the server will not have any additional data to send to the client which is the main reason to use the shutdown sequence.  If the server closes a connection, it is usually from a request processing error or that the client already closed it, so again no response is being sent.

The shutdown sequence as viewed from wireshark may depend on a number of factors.  On my virtual machine running Ubuntu 14.04, a local connection is showing a FIN, ACK sequence.  

I do see that looking at the EOF state to either indicate a warning or just information would be useful.  I'm not sure that adding the complexity of the separate shutdown/close sequencing is necessary.

**Comment by JanPlitzkow** [comment]
I see your point of a graceful shutdown being a little oversized for an rpc system. For me the whole TCP-stuff is quite new, so I don't really know if a shutdown sequencing would be better design or just unneeded complexity. After all it's probably your design decision, because if you ask three people, you'll have four opinions on how to do it right... 
Still I think the server shouldn't throw a warning for the default way of a disconnect. But if I understand you correctly, you also stated this in your last paragraph.

**Comment by JanPlitzkow** [comment]
Actually your commit is not sufficient for me, I still get the error. I would propose to write
```
bool TcpConnection::ReadHeader()
{
    // Read available data
    size_t bytesRead;
    bool eof;
    if (!socket_.Receive(buffer_+bufferLength_, MaxBufferLength-bufferLength_, bytesRead, eof))
    {
		#ifdef WIN32
    	if (eof || socket_.GetLastError()==WSAECONNRESET)
		#else
        if (eof || socket_.GetLastError()==ECONNRESET)
		#endif // WIN32
        	log_info("Client disconnect: error=" << socket_.GetLastError());
        else
            log_warn("Error while reading header: error=" << socket_.GetLastError() << ", bytesRead=" << bytesRead);
        Initialize();
        return false;
    }
```
for the TCP server. And probably similar for the html...

This works fine for me on Linux and Windows.

**Comment by sgieseking** [comment]
I'll need to see about creating this situation.  I don't totally like looking at the error code directly especially one that requires an ifdef.  This could be hidden in a new call in socket.

**Comment by JanPlitzkow** [comment]
Your solution seems to work so far. I'm going to restructure my application a little and will notice you if any issues on disconnection arise.
