### ISSUE TITLE
Additional function template for Value

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#14]
What do you think about an additional function template  for value.h?
```
//! Add member with string and any type known by value-constructor
	template<typename T>
	Value& Add2Map(const std::string& str, T& value) { Value tempValue(value); return AddMember(str.c_str(), str.length(), tempValue); }
```

Supposed the corresponding variables myString, myInt, myBool exist, instead of calls like
```
anyrpc::Value param(anyrpc::ValueType::MapType)
anyrpc::Value newMember;
newMember = anyrpc::Value( myString );
param.AddMember("print",newMember);
newMember = anyrpc::Value( myInt );
param.AddMember("number",newMember);
newMember = anyrpc::Value( myBool );
param.AddMember("boolean",newMember);
```
one could use
```
anyrpc::Value param(anyrpc::ValueType::MapType)
param.Add2Map("print",myString);
param.Add2Map("number",myInt );
param.Add2Map("boolean",myBool );
```
with the above function template. This occurs quite often for me.

Or is there any better way?

**Comment by sgieseking** [comment]
You can add members to a map using the syntax:
param["print" ] = myString;
param["number"] = myInt;
param["boolean"] = byBool;

If the member exists, it is replaced.  If the member does not exist, it is added.
See the functions:
Value& operator[](const char* str);
Value& operator[](const std::string& str);

Similar operators are available for arrays with the array automatically increasing if needed (design choice).
Value& operator[](std::size_t index);
Value& operator[](int index);

**Comment by JanPlitzkow** [comment]
Thanks, that's even better!
