### ISSUE TITLE
Maximum length of string for MsgPack is 127?!

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#17]
Hi,
on my messagepack TCP-server I've added the method
```
class Print : public anyrpc::Method
{
public:
	Print() : Method("print", "Print given information.", true) {};
	virtual void Execute(anyrpc::Value& params, anyrpc::Value& result)
	{
		if (params.IsString())
		{
			std::string sTemp(params.GetString());
			std::cout << sTemp;
		}
		result = true;
	}
};
```
On my client I'm calling
```
std::string ten("123456789_");
std::string fifty(ten+ten+ten+ten+ten);
std::string temp(fifty+fifty+ten+ten+"12345678");
anyrpc::Value param(temp), result;
myClient->Notify("print",param, result);
```
When receiving this message on the server, I get the errors
![unbenannt](https://cloud.githubusercontent.com/assets/7890485/16680838/c16231aa-44f1-11e6-9187-3cdd235ca13d.JPG)

I changed the length of the string and for me all strings of length <=127 are working. So it seems, that (2^7)-1 is the maximum lenth of a transmitted string. Is this on purpose or a bug?
Looking into the msgpack specification ( https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family ) I would expect that a maximum length of (2^32)-1 is supported. Or, if only str 8 is implemented at least (2^8)-1...

Using a JSON server and client instead, the same code works fine even with strings of length 1000 and more.

**Comment by sgieseking** [comment]
It's a bug, but only for lengths 127-255. Casting issue char/unsigned char.
