### ISSUE TITLE
Messagepack: Response parse error. Parsing was terminated.

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#18]
I've checked out the current master and compiled on Win7 with VS2015. In the exampleServer.cpp I've changed the Add function:
```
void Add(Value& params, Value& result)
{
    result.SetMap();
    result["value"] = 0;
    result["text"] = "";
    std::cout << result << std::endl;
}
```
Now calling from command line with
```
start anyrpc\build\bin\Debug\exampleServer.exe jsontcptp 9000 10
start anyrpc\build\bin\Debug\exampleClient.exe jsontcp 127.0.0.1 9000
```
on client side I get as expected the result
`success: 1, add:      {"value":0,"text":""}`

Using 
```
start anyrpc\build\bin\Debug\exampleServer.exe messagepacktcptp 9000 10
start anyrpc\build\bin\Debug\exampleClient.exe messagepacktcp 127.0.0.1 9000
```
instead, I get a parse error:
![unbenannt](https://cloud.githubusercontent.com/assets/7890485/16876583/affabfd2-4aa4-11e6-97fd-e254ed4c12fd.JPG)

The bug is probably related to using 0 as a value, but I'm not sure why.

**Comment by sgieseking** [comment]
The messagepackReader was getting confused with the integer 0 which uses a token of 0 and how it was using 0 as a special case.  It was ignoring the 0 and moving to the character in the stream so it came up one token short.
