### ISSUE TITLE
To Use With Javascript Server/Client on JSON TCP Protocol 

### ISSUE THREAD

**Issue by mekhea** [sgieseking/anyrpc#29]
Hi,
AnyRpc work fine server/client on c++. But when I use it with another Server/Client on Javascript+Node on JsonHttp is still working fine. But I used with JsonTcp no data received on server.
My Javascript code (Server and Client) work fine together on jsontcp mode also, like the AnyRpc examples. But to mix or cross it that only work on JsonHttp.
The Javascript client for example is very simple like:
var client = jayson.client.tcp({port: 9000 })
client.request('add', [3.0, 5.0], function(err,response)){... throw ....}

Any idea ?

Thanks

**Comment by sgieseking** [comment]
I glanced through the jayson source code and I didn't see that it was using netstrings for the tcp implementation, but I don't really write Javascript code.  My guess is that it is just sending the requests and responses without any encapsulation.  Jsonrpc over tcp doesn't really have a standard with some using netstrings and others not.

If the problem is the encapsulation, AnyRpc could be modified to send unencapsulated data by modifying TcpClient and TcpConnection.  The problem with not encapsulating the data is determining the ending of the JSON objects.  The structure of this code assumes that the JSON string is available before parsing, in contrast to a structure that parses a character at a time until complete.

**Comment by mekhea** [comment]
Thank you for your response
you know i used your client with jsontcp and i send request to server tcp with hercules (siftware seriak. Tcp and udp communication).
And get th request and i will send it from hercules cluent to anyrcp server. I see request with wireshark but not in your server.

 Just another information to more understand the issues
Thkx

Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by mekhea** [comment]
I modifie your cluent exactly the header...() to remove  betstring and my Javascript  server eesponse correctly  to yiur client. I have to remove this encapsulation netstrin steps (receive/send).
But what is the main raison to use this netstring and not just send and receive json native ??
Thkx

**Comment by sgieseking** [comment]
The following link summaries the encapsulation issue:
https://www.simple-is-better.org/json-rpc/transport_sockets.html

Essentially, you can only send one request/response per connection, perform some encapsulation such as netstrings, or detect the end of the JSON by some type of parsing/streaming approach.

Xmlrpc is only officially specified over http.  With jsonrpc, the spec doesn't really specify the transport layer, but with http, it is mostly consistent between implementations.  With jsonrpc tcp, some implementations encapsulate with netstrings and some don't.  

AnyRpc currently performs the encapsulation using netstrings but I can include a fully tested non-encapsulated method as an additional transport method.

**Comment by mekhea** [comment]
Hi,


Thank you again . It is very intersting to add the precompile option to decide with netstring or not. So if you can do it it will be very good . I start to modifie on clinet is more easy but not the server. The only issue is about the default request length or size. I think to use your default size of your buffer (2048 byte ). But It is more intersting for me if you do it by your self because you know it more than any other people.

Otherwise I compile your librairy on cross compile arm and the Lib linked correctly right now. I have to integrated with you cmake system. Because I just did with simple makefile under Eclipse. When I finish to work on this cross-compile and when i make it clean on your cmake I will send to you (commited).


So tell me if you will modified it to to support netstring or not ?


Thank you very much again and hope to work with you.


See you

________________________________

**Comment by sgieseking** [comment]
In the current context of processing encapsulated transfers, the default buffer of 2048 only has a requirement to hold the header (http header or netstring length).  If the entire message will fit into the buffer, that is more efficient, but it will allocate a separate buffer of up to MaxContentLength = 1000000.  If your application works better with a different default, these can be adjusted.  Another option is to modify the code to make the buffer length as a parameter when creating the class.  It's not clear whether you are suggesting that your application would benefit from a larger or smaller buffer.

Regarding modifying the code to support direct JSON as an additional communication method, I can't give you a time frame for my making the modification.
