### ISSUE TITLE
Warnings caused by type conversion

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#4]
Hello,
I'm using the AnyRPC under Win7 with Visual Studio 2015. The target application shall be compiled for 32bit and 64bit. During compilation some warnings of this kind occur:
warning C4267: 'var' : conversion from 'size_t' to 'type', possible loss of data

Under 32bit it's only 'size_t' to 'char' having problems, and the position in code can easily be handled with a simple static_cast. However, under 64bit it's also 'size_t' to 'int', 'size_t' to 'uint32_t' and others. Most of the calls refer to arguments passed between different string functions.

Example:
```
    //! Copy the string as either a short string or with allocated memory.
    void CopyString(const char* s) { CopyString(s, strlen(s)); }
    //! Copy the string as either a short string or with allocated memory.
    void CopyString(const char* s, int length);
```
strlen(s) returns a size_t, while CopyString takes an int.
Does the anyrpc library fully support 64 bit or might I run into problems later on? Any hints / comments on how to solve this warning in a most appropriate way?

**Comment by sgieseking** [comment]
Thanks for trying AnyRPC.

I'll look into this a bit more but my initial guess is that it will not cause any problems as long as the size of the various data items being transported are less than 2^31 bytes which would probably cause other buffering problems.

Under Windows x64 compilations, size_t is uint64_t, but it is being assigned to variables that are int or uint32_t.  The automatic conversion will only be a problem if the actual data is greater than 2^31 or 2^32 depending on the assignment.  

The code should be more explicit about these conversions to prevent the warning message but it also depends on the compiler and OS being used.

**Comment by sgieseking** [comment]
I looked through each of the cases that were causing a warning and I didn't see that it would cause any runtime problems.  To the question of whether it fully supports 64 bit, the only possible caveat is that structures and messages can't exceed 2^31 bytes.  I have only tested it with structures that were a few MB which is probably large for most RPC implementations anyway.

The two issues are the data size for size_t and SOCKET.  With size_t, many standard library calls return this but it seems somewhat cumbersome to use it in application code in many cases.  With SOCKET, you have the problem of certain calls such as select() requiring an int which is essentially derived from the set of sockets that are being used. So you will have to do some casting at some point.

Additionally, with the standard compilation options that cmake generates for Linux and VS, each may flag different items as a warning.  In this case, my compilation on Ubuntu x64 does not produce any warning.

I will look at cleaning up the compilation for VS Win64.  I will need to decide whether to just cast the various places where there is a warning or to change some of the data variables to a different type.

**Comment by sgieseking** [comment]
I checked in changes to clean up the Visual Studio compilation, mostly related to the Win64 version.  There are new limits on the number of member and array elements with it currently set to 16M.  These are to make sure a 64 bit size_t item doesn't cause problems by just casting to uint32_t.  If you need larger structures on a x64 compilation, the member/element count variables are uint32_t.
