### ISSUE TITLE
INADDR_LOOPBACK?

### ISSUE THREAD

**Issue by ov** [sgieseking/anyrpc#40]
Have you guys considered adding an option to use INADDR_LOOPBACK instead of INADDR_ANY in `Socket::Bind()`? The latter binds to 0.0.0.0 which triggers firewalls, while the loopback option binds to the local address without additional firewall attention.

I'm using this library as a part of Spix project, which is UI automation library and all the network communication is done locally on the host, so those firewall's notifications are quite annoying. It would be really nice to have a "local only" option somewhere in AnyRPC please :)

Thank you.

**Comment by sgieseking** [comment]
My thought is to add a new server call to set the bind address.  This would allow the user to restrict the bind to a specific address or the loopback address.  It would default to INADDR_ANY.

**Comment by ov** [comment]
That could also work, thank you.

**Comment by sgieseking** [comment]
Added a server call SetBindAddress(address).  The address needs to be in network byte order.  See exampleServer.cpp for using inet_pton() which has better Win32 support.  If you are only using Linux then inet_addr() can be used.
server->SetBindAddress(inet_addr("127.0.0.1");
server->SetBindAddress(htonl(INADDR_LOOPBACK));
