### ISSUE TITLE
select() hangs in multithread application with activated timeouts

### ISSUE THREAD

**Issue by maldag** [sgieseking/anyrpc#41]
We're using the tcp-messagepack implementation of anyrpc with enabled threading.

Upon system shutdown we're closing down the connections and sometimes it happens that select() hangs up. This can be identified using the remote debugger for ARM. We're using a timeout of 100 ms.

Furthermore, using the variable `_threadRunning` as of type `bool` is not threadsafe and should be implemented as `std::atomic`.

A possible workaroung might be to look at signals for the usage with `select()`.
http://man7.org/linux/man-pages/man2/select_tut.2.html

Has anyone considered this solution?

**Comment by sgieseking** [comment]
Which server are you using?  ServerST, ServerMT, ServerTP

Have you tried using a different one to see if the behavior changes?

When you say that select() hangs up, do you mean that the function call never returns even though the timeout is set for 100ms?  Is the main server thread hanging or is it a connection thread?

Regarding the use of signals with select(), you will need to better describe how you might use this, how it might resolve the problem, and how to keep compatibility with other rpc implementations.  

Regarding threadRunning_ and std::atomic, I think that this particular usage doesn’t have an issue but it is certainly simple to modify to use std::atomic.

**Comment by maldag** [comment]
In our application we're using `class ANYRPC_API MessagePackTcpServer : public ServerST`

On closing down the whole application the dtor calls ` Server::StopThread()`, sets `threadRunning_=false` and waits in `thread_.join();` for the thread to finish off.

The other threads runs the `Work(100)` function and exactly hangs in the select call in line server.cpp:276 `nEvents = select(static_cast<int>(maxFd) + 1, &inFd, &outFd, NULL, &tv);`

```
void Server::StopThread()
{
    log_trace();
    if (threadRunning_)
    {
        threadRunning_ = false;
		if (thread_.joinable())
			thread_.join();
		else
			log_error("Server-Thread was marked running, but was not joinable.");
    }
}

void Server::ThreadStarter()
{
    log_trace();
    while (threadRunning_ && !exit_)
    {
        Work(100);
    }
    Shutdown();
    threadRunning_ = false;
}
```

I must consider relying on timeouts on `select()` as poor architecture design since it will block indefinetly if the system call hangs or if ressources are being closed in other threads.  

After digging a bit I found two interesting discussions about safely quit  `select()` :
https://stackoverflow.com/questions/384391/how-to-signal-select-to-return-immediately
http://cr.yp.to/docs/selfpipe.html

So I haven't implemented the above ideas yet, because I'd rather hear and discuss your concerns first.

**Comment by sgieseking** [comment]
It's better to close down threads before you get to the destructors but may not be possible in your application.
Pipes run into Windows compatibility problems.
You might look at the ServerTP implementation that uses a UDP socket to interrupt the main server from the worker threads.
It's not clear that this will resolve the issue you are experiencing (since it is during the destructors) but the great thing about open source software is you can make the change and test it.
