### ISSUE TITLE
Crash on exit of examples with log4cplus

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#5]
Hello @sgieseking,

I have successfully compiled the anyrpc examples with log4cplus on Windows with Visual Studio 2015.
The examples are running fine and the logging is working.
But the application crashes on exit.
I found an issue on the log4cplus project page having the same [error](https://github.com/log4cplus/log4cplus/issues/146). However I was not able to use this information to eliminate the crash.
Simply adding `log4cplus::Initializer initializer;` to the top of the main of `exampleServer` does not fix the error.
Can you give me a few pointers how the error can be corrected?

Thank you in advance for your time and help.

Greetings
Jan

**Comment by sgieseking** [comment]
Please give a little more information on your compilation settings.   Debug/Release, x86/x64, version of log4cplus, any changes to the example log4cplus.properties file.

I had been using a version of log4cplus from about 10 months ago which was current for the original release.  I updated to the current master version, compiled as VS2015 x64 Release and didn't see a crash with executing exampleServer and exampleClient.

**Comment by JanPlitzkow** [comment]
I'm running on a Win7 64bit. I've compiled with x86, in Debug&Release mode. I'm using the original properties-file and up-to-date versions of log4cplus and anyrpc.

In order to provide you with an easy way for error reproduction, I've written a little build-script, which performes all my setup steps. The script [setupAnyRPC.txt](https://github.com/sgieseking/anyrpc/files/293231/setupAnyRPC.txt) is attached as *.txt-file, because github does not support *.bat-files.  In order to work, cmake.exe and msbuild.exe have to be on the Windows-PATH. Before running the script, I've cloned fresh copies of "anyrpc" and "log4cplus". 
My resulting setup on harddrive therefore was:
- \anyrpc
- \log4cplus
- setupAnyRPC.bat

At the end of the script exampleServer and exampleClient are automatically called. I get the following behaviour:
- `log4cplus:ERROR No appenders could be found for logger (main)`
- `log4cplus:ERROR Please initialize the log4cplus system properly`
- The clients and the server work well, even the corresponding log4cplus-warnings for invalid header are displayed
- The debug versions of client and server crash on finish
- The release version runs forever, no crash but not the expected behaviour. Without log4cplus the application immediatly closes when finished.

If I start the debug-version in VisualStudio2015 debugger I get an exception on close, which is tracked to `std::unique_lock<std::mutex> lock(this->queue_mutex);`. I'm aware, that this is inside log4cplus, but based on the [this discussion](https://github.com/log4cplus/log4cplus/issues/146) it is probably caused by the way anyrpg uses log4cplus. However - as mentioned above - I was not able to solve the problem by adding `log4cplus::Initializer initializer;` to the main functions.

Maybe my whole setup is wrong, but I hope you can check this by looking into my setup script. Besides you mentioned that anyrpc was designed with an older version of log4cplus, however I could not find any hint on the correct version / commit of log4cplus in your documentary. Therefor I'm using the current master branch.

Thanks again for your time and help!

**Comment by sgieseking** [comment]
I've mostly been using shared libraries instead of static libraries.  I'll look at it with static libraries but you might try using shared libraries.

**Comment by sgieseking** [comment]
With a static build of log4cplus, I get runtime errors that you mention. I don't see these with a shared library build.

**Comment by nagua** [comment]
The problem with the use of log4cplus within VS is this sentence in the log4cplus readme:

    log4cplus uses C++11 thread and synchronization facilities. 
    The synchronization facilities are implemented in Visual Studio C++ standard
    library in a way that utilizes global variables. Therefore it is impossible 
    (due to "static initialization order fiasco") to use them outside main().
    This issue manifests as a deadlock on exit during destruction of log4cplus' thread pool.

So with VS it is not possible at the moment to use any Logger in static functions and static variables, etc. The current use of log4cplus within anyrpc uses static loggers within the _getStaticLogger functions. I have no idea when this objects gets deconstructed. I also do not know if there are any other static uses of loggers in anyrpc.

**Comment by JanPlitzkow** [comment]
Caused by other reasons changing to Linux is not an option for some parts of my project.

I've changed my setup to use dynamic linked libraries now and the crash does not occur anymore. At least it does not break the cmd or trigger the VS debugger.
Nevertheless the program does not close as expected: If I compile with `BUILD_WITH_LOG4CPLUS=OFF`, the applications finish regularly (e.g. the exampleClient directly after finishing its job) and return error code 0. If I compile with `BUILD_WITH_LOG4CPLUS=ON`, the applications do not finish regularly but stay active forever. You can close them by clicking on the close button, but then they return with some error code != 0.
In my opinion the dll-version has the same problem with "static initialization order fiasco", but because of different procedures for dll vs lib its consequences are less severe or less visible.

At this point I can't evaluate, if the use of static loggers is needed in anyrpc. If that's the case using anyrpc without log4cplus in my final application sadly might be the only possibility under these circumstances.

**Comment by sgieseking** [comment]
A couple of options:
1. Determine a solution and submit a pull request.  This is generally how open source applications improve.  AnyRPC was written when log4cplus v1.2 was the only stable version.  Unfortunately, this version has problems compiling on VS2015.

2. Turn off log4cplus within AnyRPC as you have indicated.  You can still use log4cplus for your main application if you like how it does logging.

3. Wait for someone else to determine a solution.

In general, AnyRPC creates a static class function and not a static global variable although VS may consider these the same.  This function doesn't get the logger instance until the first call within the class.  You might try not caching the logger.  Something like:
# define log_define(category) \
   static log4cplus::Logger _getStaticLogger()   \
   {  \
	 return log4cplus::Logger::getInstance(LOG4CPLUS_TEXT(category)); \
   }
and performing the log4cplus initialization in their new format in your application:
    log4cplus::Initializer initializer;
    log4cplus::PropertyConfigurator config(LOG4CPLUS_TEXT("log4cplus.properties"));
    config.configure();

**Comment by nagua** [comment]
I will be happy to supply a pull request. But unfortunately I was not (yet) able to solve the problem.
I tried yesterday to do the change you suggested in your post, but the crash was also happening.
There are two things that I saw in the anyrpc code.

The log_define macro is not only used inside classes but also on a global scope. And I think I saw some static objects created within the library. But what I did not find was if any of these objects creates a Logger object or have running functions that created a object.
My overview of the project is a bit limited at the moment I think that is the biggest problem that I could not solve the problem.

I hope that you can provide a few pointers in that direction that we can solve the problem together.

Thank you for your time and help and the library :)

**Comment by sgieseking** [comment]
Here is what I am seeing on my compilation.  
1. Compile both log4cplus and AnyRPC using the same shared or static mode.  Don't mix compiling one as shared and the other as static.
2. Use the newer initialization for log4cplus:
log4cplus::Initializer initializer;
log4cplus::PropertyConfigurator config(LOG4CPLUS_TEXT("log4cplus.properties"));
config.configure();

I get no run-time errors in Release and Debug mode and the exampleServer and exampleClient exit without complaint.
