### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by JanPlitzkow** [sgieseking/anyrpc#8]
Hi, I'm not quite sure about this problem and the best way to solve it, that's why I have created an issue instead of a pull-request.
Similar to the exampleServer, I might create a method like this:
```
class Multiply : public Method
{
public:
    Multiply() : Method("multiply", "Multiply two numbers",true) {};
    virtual void Execute(Value& params, Value& result) { // something}
};
```
Having set deleteOnRemove to "true", the deletion of the object shall be handled by AnyRpc.
Now suppose having a correct working server, I use it like this:
```
[...]
server->GetMethodManager()->AddMethod( new Multiply );
[...]
server->GetMethodManager()->AddMethod( new Multiply );
[...]
```
By this we would create a memory leak, wouldn't we?
Looking at
```
void MethodManager::AddMethod(Method* method)
{
    MethodMap::const_iterator it = methods_.find(method->Name());
    if (it == methods_.end())
        // not found so add new method
        methods_[method->Name()] = method;
}
```
the second call would not go into the if branch, which leads to pointer beeing lost without destroying the memory.
Of course the example does not make much sense, but I'm thinking about bigger projects. Between the two AddMethod calls might be a lot of stuff, they might even be called from different source files. It even has not to be the same class which is added, if I see it correctly only the "name" of the method is relevant.

I see the following solution:
```
void MethodManager::AddMethod(Method* method)
{
    MethodMap::const_iterator it = methods_.find(method->Name());
    if (it == methods_.end())
    {
        // not found so add new method
        methods_[method->Name()] = method;
    }
    else
    {
       // some error-message???
       if method->DeleteOnRemove()
            delete method;
    }
}
```
I'm not sure if this is the best solution or if it handles all possible cases. One might also think about usage of unique_ptr. Any thoughts on this problem?

**Comment by sgieseking** [comment]
Looks right that it would leak in this case.  Generally this would be a small amount since it is usually a one-time setup issue, but not great to have.   Since the programmer should not be doing this, my thought is to throw an exception after the clean up.  If someone doesn't like having the exception thrown, they can write a local AddFunction/AddMethod function that catches the exception and ignores, but there would still be a log entry.

    void MethodManager::AddFunction(Function* function, std::string const& name, std::string const& help)
    {
        MethodMap::const_iterator it = methods_.find(name);
        if (it == methods_.end())
        {
            // not found so add new method
            methods_[name] = new MethodFunction(function,name,help);
        }
        else
        {
            // function already defined, throw exception
            anyrpc_throw(AnyRpcErrorFunctionRedefine, "Attempt to redefine function name: " + name);
        }
    }
    
    void MethodManager::AddMethod(Method* method)
    {
        MethodMap::const_iterator it = methods_.find(method->Name());
        if (it == methods_.end())
        {
            // not found so add new method
            methods_[method->Name()] = method;
        }
        else
        {
            // method already defined, clean up but still throw exception
            if (method->DeleteOnRemove())
                delete method;
            anyrpc_throw(AnyRpcErrorMethodRedefine, "Attempt to redefine method name: " + method->Name());
        }
    }

**Comment by JanPlitzkow** [comment]
Your solution looks good to me. Will you simply include it or should I make a pull request?
